### ISSUE TITLE
No Report in check-runs

### ISSUE THREAD

**Issue by sidey79** [Difegue/action-perlcritic#4]
I tryed the action, but had no luck getting a reportm out.

I think my workflow is simple

```
name: Perlcritic
on: [workflow_dispatch,pull_request]

jobs:
  critic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Perl Critic
      uses: Difegue/action-perlcritic@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
          args: ./FHEM/* 
```

And produces this in the runner logs:

```
Run Difegue/action-perlcritic@2.0.0
  with:
    args: ./FHEM/*
  env:
    GITHUB_TOKEN: ***

Getting checks
Created check null
Testing Perl code
Pushing batch of annotations ...
Pushing batch of annotations ...
Pushing batch of annotations ...
Pushing batch of annotations ...
Pushing payload to https://api.github.com/repos/RFD-FHEM/RFFHEM/check-runs/null

```

But i can't find anywhere a report.
